export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const INGREDIENT_MOVE: "INGREDIENT_MOVE" = "INGREDIENT_MOVE";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const ADD_BUNS: "ADD_BUNS" = "ADD_BUNS";
export const DELETE_ALL_INGREDIENTS: "DELETE_ALL_INGREDIENTS" = "DELETE_ALL_INGREDIENTS";